### ISSUE TITLE
rooms taking a long time to load

### ISSUE THREAD

**Issue by aahaahahah** [Julianty123/GAntiLag#3]
is there anyway to make the rooms which we removed furniture to load faster?

**Comment by Julianty123** [comment]
Honestly, that depends on your bandwidth. I think it is possible to add an option directly in the swf to hide furnis or, failing that, gantilag already hides previously saved furnis.

**Comment by aahaahahah** [comment]
if hiding furnis directly in the swf can possibly be done that would be more practical I think. I'm guessing the extension takes its time to hide the furnis and THEN it loads the room (even if I loaded the saved hidden furnis), which I don't think it has something to do with bandwidth?
Thanks for your reply, by the way.
