### ISSUE TITLE
AvoidTiles Problem

### ISSUE THREAD

**Issue by TDoomX** [Julianty123/GAntiLag#4]
Habbo recently updated and now it won't work on :avoidtiles anymore. Could you test?

**Comment by Julianty123** [comment]
Hi, what do you mean? In my extension you can hide any furniture with the checkbox control, maybe you are talking about the Lilith client? Let me to know

**Comment by TDoomX** [comment]
I'm sorry, I was talking about your GMazeRunner extension, your :tileavoid command isnt working

**Comment by Julianty123** [comment]
yep :tileavoid, it was in beta phase I think, but I don't know when it will be available again or fixed, Im sorry
